/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseGeral = new javax.swing.JPanel();
        fundo3op = new javax.swing.JPanel();
        botaoPrisma = new javax.swing.JButton();
        botaoPiramide = new javax.swing.JButton();
        botaoOutros = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lateralOpPrisma = new javax.swing.JPanel();
        TexEscolhaBasePrisma = new javax.swing.JLabel();
        botaoPrismaTri = new javax.swing.JButton();
        botaoPrismaRet = new javax.swing.JButton();
        botaoPrismaPent = new javax.swing.JButton();
        botaoPrismaHex = new javax.swing.JButton();
        botaoPrismaCirc = new javax.swing.JButton();
        fundoMeio = new javax.swing.JPanel();
        fundoPrismaTri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfieldLadoBasePrismaTri = new javax.swing.JTextField();
        tfieldAlturaPoliPrismaTri = new javax.swing.JTextField();
        botaoCalcularPrismaTri = new javax.swing.JButton();
        resultPrismaTri = new javax.swing.JLabel();
        fundoPrismaRet = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfieldLadoBasePrismaRet = new javax.swing.JTextField();
        tfieldAlturaPoliPrismaRet = new javax.swing.JTextField();
        botaoClacularPrismaRet = new javax.swing.JButton();
        resultPrismaRet = new javax.swing.JLabel();
        fundoPrismaPent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfieldLadoBasePrismaPent = new javax.swing.JTextField();
        tfieldAlturaPoliPrismaPent = new javax.swing.JTextField();
        botaoCalcularPrismaPent = new javax.swing.JButton();
        resultPrismaPent = new javax.swing.JLabel();
        fundoPrismaHex = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfieldLadoBasePrismaHex = new javax.swing.JTextField();
        tfieldAlturaPoliPrismaHex = new javax.swing.JTextField();
        botaoCalcularPrismaHex = new javax.swing.JButton();
        resultPrismaHex = new javax.swing.JLabel();
        fundoPrismaCirc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        resultPrismaCirc = new javax.swing.JLabel();
        tfieldRaioPrismaCirc = new javax.swing.JTextField();
        tfieldAlturaPrismaCirc = new javax.swing.JTextField();
        botaoCalcularPrismaCirc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(100, 100));

        fundo3op.setBackground(new java.awt.Color(204, 204, 204));

        botaoPrisma.setText("Prisma");
        botaoPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrismaActionPerformed(evt);
            }
        });

        botaoPiramide.setText("Pirâmide");

        botaoOutros.setText("Outros");

        javax.swing.GroupLayout fundo3opLayout = new javax.swing.GroupLayout(fundo3op);
        fundo3op.setLayout(fundo3opLayout);
        fundo3opLayout.setHorizontalGroup(
            fundo3opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo3opLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(botaoPrisma)
                .addGap(281, 281, 281)
                .addComponent(botaoPiramide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 561, Short.MAX_VALUE)
                .addComponent(botaoOutros)
                .addGap(107, 107, 107))
        );
        fundo3opLayout.setVerticalGroup(
            fundo3opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo3opLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(fundo3opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPrisma)
                    .addComponent(botaoPiramide)
                    .addComponent(botaoOutros))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        lateralOpPrisma.setBackground(new java.awt.Color(153, 153, 153));
        lateralOpPrisma.setLayout(new java.awt.CardLayout());

        TexEscolhaBasePrisma.setText("Escolha o formato da base:");
        lateralOpPrisma.add(TexEscolhaBasePrisma, "card2");

        botaoPrismaTri.setText("Triangular");
        lateralOpPrisma.add(botaoPrismaTri, "card3");

        botaoPrismaRet.setText("Retangular");
        lateralOpPrisma.add(botaoPrismaRet, "card4");

        botaoPrismaPent.setText("Pentagonal");
        lateralOpPrisma.add(botaoPrismaPent, "card5");

        botaoPrismaHex.setText("Hexagonal");
        lateralOpPrisma.add(botaoPrismaHex, "card6");

        botaoPrismaCirc.setText("Circular");
        lateralOpPrisma.add(botaoPrismaCirc, "card7");

        jPanel2.add(lateralOpPrisma, "card2");

        fundoMeio.setLayout(new java.awt.CardLayout());

        jLabel1.setText("prisma de base triangular");

        tfieldLadoBasePrismaTri.setText("Lado da base");

        tfieldAlturaPoliPrismaTri.setText("Altura do poliedro");

        botaoCalcularPrismaTri.setText("Calcular!");

        resultPrismaTri.setText("Resultado:");

        javax.swing.GroupLayout fundoPrismaTriLayout = new javax.swing.GroupLayout(fundoPrismaTri);
        fundoPrismaTri.setLayout(fundoPrismaTriLayout);
        fundoPrismaTriLayout.setHorizontalGroup(
            fundoPrismaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                .addGroup(fundoPrismaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(fundoPrismaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCalcularPrismaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                                .addComponent(tfieldLadoBasePrismaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(242, 242, 242)
                                .addComponent(tfieldAlturaPoliPrismaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(resultPrismaTri)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        fundoPrismaTriLayout.setVerticalGroup(
            fundoPrismaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaTriLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addGroup(fundoPrismaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldLadoBasePrismaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAlturaPoliPrismaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(botaoCalcularPrismaTri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(resultPrismaTri)
                .addGap(106, 106, 106))
        );

        fundoMeio.add(fundoPrismaTri, "card2");

        jLabel2.setText("jLabel2");

        tfieldLadoBasePrismaRet.setText("Lado da base");

        tfieldAlturaPoliPrismaRet.setText("Altura");

        botaoClacularPrismaRet.setText("Calcular!");

        resultPrismaRet.setText("Resultado:");

        javax.swing.GroupLayout fundoPrismaRetLayout = new javax.swing.GroupLayout(fundoPrismaRet);
        fundoPrismaRet.setLayout(fundoPrismaRetLayout);
        fundoPrismaRetLayout.setHorizontalGroup(
            fundoPrismaRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(tfieldLadoBasePrismaRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfieldAlturaPoliPrismaRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                .addGroup(fundoPrismaRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(botaoClacularPrismaRet, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(resultPrismaRet)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        fundoPrismaRetLayout.setVerticalGroup(
            fundoPrismaRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaRetLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(122, 122, 122)
                .addGroup(fundoPrismaRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldLadoBasePrismaRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAlturaPoliPrismaRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addComponent(botaoClacularPrismaRet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(resultPrismaRet)
                .addGap(79, 79, 79))
        );

        fundoMeio.add(fundoPrismaRet, "card3");

        jLabel3.setText("Prisma base pentagonal");

        tfieldLadoBasePrismaPent.setText("lado da base");

        tfieldAlturaPoliPrismaPent.setText("Altura do poliedro");

        botaoCalcularPrismaPent.setText("Calcular!");

        resultPrismaPent.setText("Resultado:");

        javax.swing.GroupLayout fundoPrismaPentLayout = new javax.swing.GroupLayout(fundoPrismaPent);
        fundoPrismaPent.setLayout(fundoPrismaPentLayout);
        fundoPrismaPentLayout.setHorizontalGroup(
            fundoPrismaPentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaPentLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(tfieldLadoBasePrismaPent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(tfieldAlturaPoliPrismaPent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(fundoPrismaPentLayout.createSequentialGroup()
                .addGroup(fundoPrismaPentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPrismaPentLayout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(botaoCalcularPrismaPent))
                    .addGroup(fundoPrismaPentLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(fundoPrismaPentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultPrismaPent)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoPrismaPentLayout.setVerticalGroup(
            fundoPrismaPentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaPentLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(104, 104, 104)
                .addGroup(fundoPrismaPentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldLadoBasePrismaPent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAlturaPoliPrismaPent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(botaoCalcularPrismaPent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(resultPrismaPent)
                .addGap(76, 76, 76))
        );

        fundoMeio.add(fundoPrismaPent, "card4");

        jLabel4.setText("Prisma base hexagonal");

        tfieldLadoBasePrismaHex.setText("Lado da base");

        tfieldAlturaPoliPrismaHex.setText("Altura poliedro");

        botaoCalcularPrismaHex.setText("Calcular!");

        resultPrismaHex.setText("Resultado:");

        javax.swing.GroupLayout fundoPrismaHexLayout = new javax.swing.GroupLayout(fundoPrismaHex);
        fundoPrismaHex.setLayout(fundoPrismaHexLayout);
        fundoPrismaHexLayout.setHorizontalGroup(
            fundoPrismaHexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaHexLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(tfieldLadoBasePrismaHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(tfieldAlturaPoliPrismaHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(fundoPrismaHexLayout.createSequentialGroup()
                .addGroup(fundoPrismaHexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPrismaHexLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(botaoCalcularPrismaHex))
                    .addGroup(fundoPrismaHexLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(fundoPrismaHexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultPrismaHex)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoPrismaHexLayout.setVerticalGroup(
            fundoPrismaHexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaHexLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addGap(129, 129, 129)
                .addGroup(fundoPrismaHexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldLadoBasePrismaHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAlturaPoliPrismaHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(botaoCalcularPrismaHex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(resultPrismaHex)
                .addGap(60, 60, 60))
        );

        fundoMeio.add(fundoPrismaHex, "card5");

        jLabel5.setText("Prisma base circular");

        resultPrismaCirc.setText("Resultado:");

        tfieldRaioPrismaCirc.setText("Raio da base");

        tfieldAlturaPrismaCirc.setText("Altura poliedro");

        botaoCalcularPrismaCirc.setText("Calcular!");

        javax.swing.GroupLayout fundoPrismaCircLayout = new javax.swing.GroupLayout(fundoPrismaCirc);
        fundoPrismaCirc.setLayout(fundoPrismaCircLayout);
        fundoPrismaCircLayout.setHorizontalGroup(
            fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaCircLayout.createSequentialGroup()
                .addGroup(fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundoPrismaCircLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(tfieldRaioPrismaCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addGroup(fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fundoPrismaCircLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addGroup(fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resultPrismaCirc)
                                .addComponent(jLabel5)))
                        .addGroup(fundoPrismaCircLayout.createSequentialGroup()
                            .addGap(354, 354, 354)
                            .addComponent(botaoCalcularPrismaCirc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(tfieldAlturaPrismaCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        fundoPrismaCircLayout.setVerticalGroup(
            fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPrismaCircLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addGap(126, 126, 126)
                .addGroup(fundoPrismaCircLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldRaioPrismaCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAlturaPrismaCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(botaoCalcularPrismaCirc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(resultPrismaCirc)
                .addGap(92, 92, 92))
        );

        fundoMeio.add(fundoPrismaCirc, "card6");

        jPanel2.add(fundoMeio, "card3");

        javax.swing.GroupLayout baseGeralLayout = new javax.swing.GroupLayout(baseGeral);
        baseGeral.setLayout(baseGeralLayout);
        baseGeralLayout.setHorizontalGroup(
            baseGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo3op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(baseGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(baseGeralLayout.createSequentialGroup()
                    .addGap(460, 460, 460)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );
        baseGeralLayout.setVerticalGroup(
            baseGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseGeralLayout.createSequentialGroup()
                .addComponent(fundo3op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(844, Short.MAX_VALUE))
            .addGroup(baseGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(baseGeralLayout.createSequentialGroup()
                    .addGap(321, 321, 321)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPrismaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TexEscolhaBasePrisma;
    private javax.swing.JPanel baseGeral;
    private javax.swing.JButton botaoCalcularPrismaCirc;
    private javax.swing.JButton botaoCalcularPrismaHex;
    private javax.swing.JButton botaoCalcularPrismaPent;
    private javax.swing.JButton botaoCalcularPrismaTri;
    private javax.swing.JButton botaoClacularPrismaRet;
    private javax.swing.JButton botaoOutros;
    private javax.swing.JButton botaoPiramide;
    private javax.swing.JButton botaoPrisma;
    private javax.swing.JButton botaoPrismaCirc;
    private javax.swing.JButton botaoPrismaHex;
    private javax.swing.JButton botaoPrismaPent;
    private javax.swing.JButton botaoPrismaRet;
    private javax.swing.JButton botaoPrismaTri;
    private javax.swing.JPanel fundo3op;
    private javax.swing.JPanel fundoMeio;
    private javax.swing.JPanel fundoPrismaCirc;
    private javax.swing.JPanel fundoPrismaHex;
    private javax.swing.JPanel fundoPrismaPent;
    private javax.swing.JPanel fundoPrismaRet;
    private javax.swing.JPanel fundoPrismaTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lateralOpPrisma;
    private javax.swing.JLabel resultPrismaCirc;
    private javax.swing.JLabel resultPrismaHex;
    private javax.swing.JLabel resultPrismaPent;
    private javax.swing.JLabel resultPrismaRet;
    private javax.swing.JLabel resultPrismaTri;
    private javax.swing.JTextField tfieldAlturaPoliPrismaHex;
    private javax.swing.JTextField tfieldAlturaPoliPrismaPent;
    private javax.swing.JTextField tfieldAlturaPoliPrismaRet;
    private javax.swing.JTextField tfieldAlturaPoliPrismaTri;
    private javax.swing.JTextField tfieldAlturaPrismaCirc;
    private javax.swing.JTextField tfieldLadoBasePrismaHex;
    private javax.swing.JTextField tfieldLadoBasePrismaPent;
    private javax.swing.JTextField tfieldLadoBasePrismaRet;
    private javax.swing.JTextField tfieldLadoBasePrismaTri;
    private javax.swing.JTextField tfieldRaioPrismaCirc;
    // End of variables declaration//GEN-END:variables
}
